"use client";
import { useState, useEffect, type FormEvent } from "react";
import { Checkbox } from "@/components/ui/checkbox";
import { Compass, Sprout, AudioLines } from "lucide-react";
import ExplorationDemo, { PlantPreview } from "./exploration-demo";
export default function Home(){
 const [testing,setTesting]=useState(false),[email,setEmail]=useState("");
 const [status,setStatus]=useState<"idle"|"saving"|"success"|"error">("idle"),[error,setError]=useState(""),[removalToken,setRemovalToken]=useState<string|null>(null);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;
  if(!context)return;
  const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({
   name:"stage_waitlist_signup",title:"Prepare a waitlist signup",
   description:"Fill the visible waitlist form with an email and optional paid-testing interest. Does not submit or save the signup; the visitor must review and submit the form.",
   inputSchema:{type:"object",properties:{email:{type:"string"},testing:{type:"boolean"}},required:["email","testing"],additionalProperties:false},
   annotations:{readOnlyHint:false,untrustedContentHint:false},
   execute(input:unknown){const p=input as {email?:unknown;testing?:unknown};if(typeof p.email!=="string"||!/^\S+@\S+\.\S+$/.test(p.email)||p.email.length>254||typeof p.testing!=="boolean")throw new Error("Provide a valid email and a boolean testing preference.");setEmail(p.email);setTesting(p.testing);setStatus("idle");document.getElementById("waitlist")?.scrollIntoView();return {staged:true,submitted:false};}
  },{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 async function join(event:FormEvent<HTMLFormElement>){
  event.preventDefault(); const website=new FormData(event.currentTarget).get("website"); setStatus("saving");
  try{const r=await fetch("/api/waitlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,testing,website})});const data=await r.json() as {error?:string;removalToken?:string};if(!r.ok)throw new Error(data.error||"We couldn’t save your signup. Please try again.");setRemovalToken(data.removalToken||null);setStatus("success");}catch(e){setError(e instanceof Error?e.message:"Please try again.");setStatus("error");}
 }
 return <>
 <a className="skip" href="#main">Skip to content</a>
 <header className="site-header wrap"><a className="wordmark" href="#" aria-label="Present Tense home"><span className="brand-symbol" aria-hidden="true">pt.</span>Present Tense</a><nav aria-label="Main navigation"><a href="#approach">The app</a><a href="#explore">A closer look</a><a className="nav-cta" href="#waitlist">Join the waitlist</a></nav></header>
 <main id="main">
 <section className="hero wrap"><div className="hero-copy"><p className="eyebrow">For your sense of self and agency · In development</p><h1>Make room<br/>for <em>yourself.</em></h1><p className="lead">Your feelings. Your interests. Your choices.</p><p className="intro">Present Tense helps you stay connected to who you are and what you want—and bring that sense of yourself into your everyday situations and decisions, even when technology, circumstances, or other people pull you in another direction.</p><div className="hero-actions"><a className="button" href="#waitlist">Join the waitlist</a><a className="text-link" href="#approach">Get to know the app</a></div><p className="small-note">Mobile and web planned. Taking shape, thoughtfully.</p></div>
 <figure className="hero-prototype"><div className="plant-display"><PlantPreview/></div><figcaption>Give a part of yourself a presence you can carry into what comes next.</figcaption></figure></section>
 <section className="recognition"><div className="wrap recognition-inner"><p className="eyebrow">When your own voice gets crowded out</p><h2>Sometimes, you need a moment<br/> to ask: <em>“What do I actually want?”</em></h2><div className="situations"><p>Before another automatic scroll.</p><p>When belonging starts to feel like obligation.</p><p>When other demands leave little room for what matters to you.</p></div><p className="recognition-close">Present Tense is being built to help you pause, make space for what emerges, and carry that sense of yourself into what you do next.</p></div></section>
 <section id="approach" className="section wrap"><div className="section-heading"><p className="eyebrow">Your sense of self, in the midst of life</p><h2>Ground yourself. Choose from there.</h2><p>Notice what matters to you, give it a tangible presence, and let it inform how you respond to the world around you.</p></div><div className="feature-grid">
 <article className="feature"><span className="feature-number">01</span><Compass size={30} strokeWidth={1.3}/><h3>Check-Ins</h3><p className="feature-subtitle">Pause where pressure meets you.</p><p>Bring your own questions into moments of pressure, so your feelings and intentions have a place in what you choose next. Write your own questions and answer options, or adapt a template.</p><div className="example"><span>For example</span><p>“What do you want this platform to be for today?”</p></div><p className="feature-foot">Planned triggers include chosen times and opening selected apps.</p></article>
 <article className="feature"><span className="feature-number">02</span><Sprout size={30} strokeWidth={1.3}/><h3>Self-Explorations</h3><p className="feature-subtitle">Give what matters to you a presence.</p><p>Explore interests, feelings, relationships, and intentions through virtual objects. Write into a leaf, change a stone’s size to express how much is being asked of you, or represent the distance you want from a community.</p><div className="example"><span>For example</span><p>Making room for discomfort in a community, and letting it guide whether you want to stay.</p></div><p className="feature-foot">Keep these pieces of yourself present as you navigate relationships, demands, and decisions.</p></article>
 <article className="feature"><span className="feature-number">03</span><AudioLines size={30} strokeWidth={1.3}/><h3>Self-Records</h3><p className="feature-subtitle">Keep the world that feels like yours.</p><p>Gather traces of your lived experience: images from an ordinary day, familiar ambient sounds, and the places and moments intertwined with your sense of self.</p><div className="example"><span>For example</span><p>The sound of a familiar place. A day in small pictures.</p></div><p className="feature-foot">Revisit what grounds you as you navigate new situations. This feature is still being developed.</p></article>
 </div></section>
 <section id="explore" className="explore-section"><div className="wrap explore-grid"><div><p className="eyebrow">Inside Self-Explorations</p><h2>A part of you.<br/>Present in your life.</h2><p className="explore-intro">In the plant exploration, each leaf can carry something that feels like you. Choose a category, put it into your own words, and give it a place on your plant.</p><p>A leaf gives that part of you a presence beyond the moment of reflection. Revisit it before a difficult conversation or a busy week: your humorous side can have a place in how you relate to others; your love of drawing can have a say when you decide how to spend your time.</p><p className="small-note" style={{marginTop:24}}>Try choosing a category and writing into the leaf. What would keeping that part of yourself present change about your next choice?</p></div><ExplorationDemo/></div></section>
 <section className="section wrap faq-section"><div><p className="eyebrow">As the app takes shape</p><h2>A few things<br/> you might wonder.</h2></div><div className="faqs">
 <details><summary>Who is Present Tense for?</summary><p>People who feel that outside pressures are crowding out their own feelings, interests, or choices. You might be rethinking a digital habit, a relationship, or where you feel you belong. The app’s initial audience is still being explored.</p></details>
 <details><summary>When and where will it be available?</summary><p>Present Tense is in development, with mobile and web planned. There is no announced launch date. Features and platform support may change as the prototype is refined.</p></details>
 <details><summary>What about my entries and AI?</summary><p>Storage options are still being decided, including keeping entries on your device and syncing to an account. The intended core experience does not require AI. Any AI tools offered in a future version are intended to be optional. Final privacy and storage details will be shared before release.</p></details>
 <details><summary>What would paid user testing involve?</summary><p>The current idea is to try the app while the creator asks questions and observes how it works for you. Sessions are expected to take no more than 40 minutes. The format, exact length, eligibility, and compensation are not yet settled and will be confirmed before you agree to participate. Expressing interest does not commit you to taking part.</p></details>
 </div></section>
 <section id="waitlist" className="waitlist-section"><div className="wrap waitlist-grid"><div><p className="eyebrow">Be here for what comes next</p><h2>Make room for yourself.<br/><em>In the life you live.</em></h2><p>Join the waitlist for development and launch updates. If you’d like, you can also express interest in helping shape Present Tense through paid user testing.</p></div><div className="signup-card">{status==="success"?<div className="success" role="status"><Sprout size={40}/><h3>You’re on the list.</h3><p>Thank you for your interest in Present Tense.</p>{removalToken ? <p><a className="text-link" href={"/remove#token="+removalToken}>Your personal removal link</a><br/>Save this link privately in case you want to leave the list.</p> : <p>If you signed up before, your original entry and testing preference are unchanged.</p>}<p>{removalToken && testing?"Your interest in paid user testing has also been saved. Details will be shared before you decide whether to participate.":"You’ll hear about development and launch updates."}</p></div>:<form onSubmit={join}><label htmlFor="email">Your email address</label><input id="email" name="email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><div className="testing-choice"><Checkbox id="testing" checked={testing} onCheckedChange={v=>setTesting(v===true)}/><label htmlFor="testing">I’m also interested in paid user testing<span>Optional. Details and compensation to be confirmed.</span></label></div><button className="button" type="submit" disabled={status==="saving"}>{status==="saving"?"Joining…":"Join the waitlist"}</button>{status==="error"&&<p className="form-error" role="alert">{error}</p>}<p className="consent">By joining, you agree to receive Present Tense updates and, if selected, testing invitations. Your email and testing preference will be stored for these purposes. <a href="/privacy">Signup privacy & removal</a></p></form>}</div></div></section>
 </main><footer className="wrap"><a className="wordmark" href="#">Present Tense</a><p>Make room for yourself.</p><a href="/privacy">Signup privacy</a><span>In development · © 2026 Present Tense</span></footer>
 </>;
}
